[package]
name = "win-screenshot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24"
winapi = { version = "0.3", features = ["winuser", "processthreadsapi", "libloaderapi",
    "handleapi", "psapi", "errhandlingapi", "impl-default", "utilapiset", "winerror"] }

