[package]
name = "win-screenshot"
version = "1.0.2"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Take a screenshot from specified window or entire screen on Windows platform"
readme = "README.md"
repository = "https://github.com/h04x/win-screenshot"
homepage = "https://github.com/h04x/win-screenshot"
documentation = "https://docs.rs/win-screenshot"
authors = ["h04x <distract.doctrine@gmail.com>"]
keywords = ["screenshot", "display", "window", "windows", "screen"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
targets = ["x86_64-pc-windows-msvc"]


[dependencies]
image = "0.24"
windows = { version = "0.37", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_Graphics_Gdi", "Win32_Storage_Xps"] }

[dev-dependencies]
regex = "1"

